### PR TITLE
Dlr/2021 04 01 more version info

### PR DESCRIPTION
**Pull request by pdlr**
Seems like the LibMultiSense utility programs should include a way to check what firmware version is on your camera, so I've added that output to DeviceInfoUtility.

### CODE REVIEW

**Comment by mattalvarado** [comment]
I like the idea, but I think this might be better suited for something like a VersionInfoUtility.

For development I sometimes query the current device info, pipe the result to a file, make modifications to the file, and load the modified device info back on the camera. While our loading routine is resilient to the addition of this extra data, I think it's a bit confusing if it is loaded an ignored by the camera. A developer might think they can update the version parameters via the device info utility, when they are really just compiled into the firmware.

I am open to push back on this opinion. Not sure if you already considered the above use case while implementing.

**Comment by pdlr** [comment]
I did not consider that use case, and I agree with you that VersionInfoUtility is a better solution all-around.  I'll do that instead.  Stand by for more commits...

**Comment by pdlr** [comment]
Ready for re-review.

**Review by mattalvarado — APPROVED** [review]
Looks great! Thanks @pdlr!

**Pull request merged**
