### PR TITLE
Add utility to set the rectified focal length

### PR DESCRIPTION
**Pull request by mattalvarado**
Add a utility to set the rectified focal length. This allows customers to manually adjust the FOV of their rectified images.

### CODE REVIEW

**Comment by oamidi** [comment]
Hi,


Maybe there should be higher lower limit for the focal length. I saw it checks that it's non-negative.  Maybe 200 pixels?

Also, We need to be careful that the focal length is not too low so that there are cache misses and the pipeline slows down.
Right now, we don't have a good way of finding that lower limit.

Thinking about it.

**Comment by mattalvarado** [comment]
> Hi,
> 
> Maybe there should be higher lower limit for the focal length. I saw it checks that it's non-negative. Maybe 200 pixels?
> 
> Also, We need to be careful that the focal length is not too low so that there are cache misses and the pipeline slows down. Right now, we don't have a good way of finding that lower limit.
> 
> Thinking about it.

Updated to require a minimum of 200 pixels for now. The camera could do the check internally since it knows the how far things need to jump in memory.

**Comment by mattalvarado** [comment]
@oamidi Any feedback on this?

**Review by oamidi — APPROVED** [review]

**Comment by mattalvarado** [comment]
> Hi. Sorry. This is all good. If a focal length can be presented via libmultisense, the camera can adjust the remap tables to accommodate.

Yep, this uses LibMultiSense to send the update to the camera when the `-s` argument is supplied.

**Pull request merged**
